#!/usr/bin/env zsh -i

cat <<- "EOF"

     _
    | |
 ___| | __ _ _ __  ___  ___ _ __ ___  ___ _ __
/ __| |/ _` | '_ \/ __|/ __| '__/ _ \/ _ \ '_ \
\__ \ | (_| | |_) \__ \ (__| | |  __/  __/ | | |
|___/_|\__,_| .__/|___/\___|_|  \___|\___|_| |_|
       | |
       |_|
              by Jack MapelLentz (https://jltml.me)

EOF

cat <<- "EOF"

┌─────────────────────────────────────────────┐
│          !! type control-c to quit          │
│   otherwise you will leave things running   │
└─────────────────────────────────────────────┘

EOF

printf "=> Stopping conflicting processes\n"
  if pgrep -f "redis-server"; then
    printf "=> Stopping running redis-server process\n"
    printf "=> kill -2 $(pgrep -f "redis-server")\n"
    kill -2 $(pgrep -f "redis-server")
  fi

printf "=> cd $(dirname "$0")\n"
  cd $(dirname "$0")

printf "=> OPEN_SLAPSCREEN=true $(dirname \"$0\")/bin/dev\n"
  OPEN_SLAPSCREEN=true $(dirname "$0")/bin/dev
